import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { router } from 'expo-router';
import { AppButton, Eyebrow, Field, Screen, Title } from '@/src/components/ui';
import { AnimatedEntrance } from '@/src/components/motion';
import { todayIso } from '@/src/lib/dates';
import { getTheme } from '@/src/lib/tokens';
import { useSavePlant } from '@/src/hooks/usePlants';
import { useResponsiveLayout } from '@/src/hooks/useResponsiveLayout';

export default function NewPlantScreen() {
  const [name, setName] = useState(''); const [species, setSpecies] = useState(''); const [days, setDays] = useState('7'); const [error, setError] = useState<string | null>(null); const save = useSavePlant(); const t = getTheme(useColorScheme()); const layout = useResponsiveLayout();
  const submit = async () => { const wateringDays = Number(days); if (!name.trim() || !species.trim() || !Number.isInteger(wateringDays) || wateringDays < 1) { setError('Nhập tên, loài và chu kỳ tưới là số nguyên dương.'); return; } setError(null); await save.create.mutateAsync({ name: name.trim(), species: species.trim(), wateringDays, lastWatered: todayIso() }); router.replace('/'); };
  return <Screen padded={false}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={styles.flex}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[styles.content, { paddingHorizontal: layout.horizontalPadding, paddingTop: layout.verticalPadding, gap: layout.compact ? 12 : 16 }]}><AnimatedEntrance><View style={[styles.hero, { padding: layout.compact ? 14 : 18, backgroundColor: t.accent, borderColor: t.accentStrong }]}><Text style={styles.heroIcon}>🌱</Text><View style={{ flex: 1, minWidth: 0 }}><Eyebrow>Bộ sưu tập mới</Eyebrow><Title>Thêm một cây</Title><Text style={{ color: t.muted }}>Tạo lịch tưới riêng để không bỏ lỡ lần chăm sóc tiếp theo.</Text></View></View></AnimatedEntrance><AnimatedEntrance delay={80}><View style={[styles.tip, { backgroundColor: t.primarySoft }]}><Text style={styles.tipIcon}>💡</Text><View style={styles.tipCopy}><Text style={[styles.tipText, { color: t.text }]}>Gợi ý: bắt đầu với chu kỳ 7 ngày, rồi điều chỉnh theo tình trạng đất.</Text></View></View></AnimatedEntrance><AnimatedEntrance delay={130}><View style={styles.form}><Field label="Tên cây" value={name} onChangeText={setName} placeholder="Ví dụ: Lan ý" /><Field label="Loài" value={species} onChangeText={setSpecies} placeholder="Ví dụ: Spathiphyllum" /><Field label="Chu kỳ tưới (ngày)" value={days} onChangeText={setDays} placeholder="7" keyboardType="numeric" />{error ? <View accessibilityRole="alert" style={[styles.error, { backgroundColor: t.dangerSoft }]}><Text style={{ color: t.danger }}>{error}</Text></View> : null}<AppButton label={save.create.isPending ? 'Đang lưu cây...' : 'Lưu cây vào khu vườn'} onPress={() => void submit()} disabled={save.create.isPending} /><AppButton label="Hủy" tone="secondary" onPress={() => router.back()} /></View></AnimatedEntrance></ScrollView></KeyboardAvoidingView></Screen>;
}

const styles = StyleSheet.create({ flex: { flex: 1 }, content: { paddingBottom: 32 }, hero: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderRadius: 24, gap: 12 }, heroIcon: { fontSize: 34 }, tip: { borderRadius: 18, padding: 14, flexDirection: 'row', gap: 10, alignItems: 'flex-start' }, tipIcon: { flexShrink: 0, fontSize: 20, lineHeight: 24 }, tipCopy: { flex: 1, minWidth: 0 }, tipText: { flexShrink: 1, fontSize: 16, lineHeight: 23 }, form: { gap: 14 }, error: { borderRadius: 14, padding: 12 } });
