import { useEffect, useMemo, useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { Redirect, router } from 'expo-router';
import { AppButton, Body, Eyebrow, Field, Loadable, OfflineBanner, Screen, Title } from '@/src/components/ui';
import { AnimatedEntrance } from '@/src/components/motion';
import { PlantCard } from '@/src/components/PlantCard';
import { useResponsiveLayout } from '@/src/hooks/useResponsiveLayout';
import { isOverdue } from '@/src/lib/dates';
import { getTheme } from '@/src/lib/tokens';
import { usePlants } from '@/src/hooks/usePlants';
import { selectOffline, selectPendingCount, useAppStore } from '@/src/store/appStore';

export default function PlantsScreen() {
  const session = useAppStore((state) => state.session); const offline = useAppStore(selectOffline); const pending = useAppStore(selectPendingCount); const cachePlants = useAppStore((state) => state.cachePlants);
  const query = usePlants(); const [search, setSearch] = useState(''); const [species, setSpecies] = useState('Tất cả'); const t = getTheme(useColorScheme()); const layout = useResponsiveLayout();
  useEffect(() => { if (query.data) void cachePlants(query.data); }, [cachePlants, query.data]);
  const speciesOptions = useMemo(() => ['Tất cả', ...new Set((query.data ?? []).map((plant) => plant.species))], [query.data]);
  const filtered = useMemo(() => (query.data ?? []).filter((plant) => plant.name.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')) && (species === 'Tất cả' || plant.species === species)), [query.data, search, species]);
  if (!session) return <Redirect href="/login" />;
  const overdue = (query.data ?? []).filter((plant) => isOverdue(plant)).length;
  const header = <DashboardHeader offline={offline} pending={pending} overdue={overdue} total={query.data?.length ?? 0} search={search} species={species} speciesOptions={speciesOptions} onSearch={setSearch} onSpecies={setSpecies} resultCount={filtered.length} />;
  return <Screen padded={false}><Loadable loading={query.isLoading} error={query.error} empty={!query.data?.length} retry={() => void query.refetch()}><FlatList data={filtered} keyExtractor={(item) => item.id} contentContainerStyle={[styles.listContent, { paddingHorizontal: layout.horizontalPadding, paddingTop: layout.verticalPadding }]} ListHeaderComponent={header} ListEmptyComponent={<View style={[styles.filterEmpty, { backgroundColor: t.accent }]}><Text style={{ fontSize: 32 }}>🔎</Text><Body>Không có cây phù hợp với bộ lọc này.</Body></View>} renderItem={({ item, index }) => <PlantCard plant={item} index={index} onPress={() => router.push({ pathname: '/plant/[id]', params: { id: item.id } })} />} /></Loadable></Screen>;
}

function DashboardHeader({ offline, pending, overdue, total, search, species, speciesOptions, onSearch, onSpecies, resultCount }: { offline: boolean; pending: number; overdue: number; total: number; search: string; species: string; speciesOptions: string[]; onSearch: (value: string) => void; onSpecies: (value: string) => void; resultCount: number }) {
  const t = getTheme(useColorScheme()); const layout = useResponsiveLayout(); const healthy = Math.max(total - overdue, 0);
  return <View style={[styles.header, { gap: layout.compact ? 14 : 18 }]}><AnimatedEntrance><View style={[styles.hero, { backgroundColor: t.primary, shadowColor: t.shadow, padding: layout.compact ? 16 : 18 }]}><View style={styles.heroTop}><View style={styles.heroText}><Text style={[styles.heroEyebrow, { color: t.primaryText }]}>PLANT CARE</Text><Text accessibilityRole="header" numberOfLines={1} adjustsFontSizeToFit style={[styles.heroTitle, { color: t.primaryText, fontSize: layout.isNarrow ? 27 : 30 }]}>Chào khu vườn</Text></View><Text accessibilityLabel="Biểu tượng cây" style={[styles.heroEmoji, { fontSize: layout.compact ? 36 : 42 }]}>🌿</Text></View><Text style={[styles.heroCopy, { color: t.primaryText }]}>Chăm đều mỗi ngày, cây sẽ khỏe hơn từng chút.</Text><View style={styles.heroPill}><Text style={{ color: t.primaryText, fontWeight: '800' }}>{offline ? 'Đang làm việc ngoại tuyến' : 'Đã đồng bộ hôm nay'}</Text></View></View></AnimatedEntrance><AnimatedEntrance delay={80}><View style={styles.statRow}><StatCard value={overdue} label="Cần tưới" color={overdue ? t.danger : t.text} /><StatCard value={healthy} label="Đang ổn" color={t.success} /><StatCard value={total} label="Tổng cây" color={t.text} /></View></AnimatedEntrance>{offline ? <OfflineBanner text={`Ngoại tuyến: đang dùng bản lưu gần nhất.${pending ? ` Có ${pending} thay đổi đang chờ đồng bộ.` : ''}`} /> : null}<AnimatedEntrance delay={120}><View style={styles.sectionHead}><View><Eyebrow>Bộ sưu tập</Eyebrow><Title>Cây của tôi</Title></View><Pressable accessibilityRole="button" accessibilityLabel="Mở cài đặt" onPress={() => router.push('/settings')} style={[styles.settings, { backgroundColor: t.accent }]}><Text style={{ fontSize: 20 }}>⚙️</Text></Pressable></View><Field label="Tìm cây theo tên" value={search} onChangeText={onSearch} placeholder="Ví dụ: Monstera" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} style={styles.chipScroll}>{speciesOptions.map((option) => <Pressable key={option} accessibilityRole="button" accessibilityLabel={`Lọc loài ${option}`} accessibilityState={{ selected: species === option }} onPress={() => onSpecies(option)} style={({ pressed }) => [styles.chip, { borderColor: species === option ? t.primary : t.border, backgroundColor: species === option ? t.primary : t.surface, opacity: pressed ? 0.75 : 1 }]}><Text numberOfLines={1} style={{ color: species === option ? t.primaryText : t.text, fontWeight: '800' }}>{option}</Text></Pressable>)}</ScrollView><AppButton label="＋ Thêm cây mới" onPress={() => router.push('/plant/new')} /></AnimatedEntrance><View style={styles.listTitle}><Text style={[styles.listTitleText, { color: t.text }]}>Danh sách cây</Text><Text style={{ color: t.muted }}>{resultCount} kết quả</Text></View></View>;
}

function StatCard({ value, label, color }: { value: number; label: string; color: string }) { const t = getTheme(useColorScheme()); const layout = useResponsiveLayout(); return <View style={[styles.statCard, { backgroundColor: t.surface, borderColor: t.border, minHeight: layout.compact ? 74 : 82, padding: layout.compact ? 10 : 12 }]}><Text adjustsFontSizeToFit numberOfLines={1} style={[styles.statValue, { color }]}>{value}</Text><Text numberOfLines={2} style={[styles.statLabel, { color: t.muted }]}>{label}</Text></View>; }

const styles = StyleSheet.create({
  listContent: { paddingBottom: 32 }, header: { marginBottom: 12 }, hero: { borderRadius: 26, gap: 10, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 18, elevation: 4 }, heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, heroText: { flex: 1, minWidth: 0 }, heroEyebrow: { fontSize: 11, fontWeight: '900', letterSpacing: 1.1 }, heroTitle: { fontWeight: '900', letterSpacing: -0.7 }, heroEmoji: { marginLeft: 10 }, heroCopy: { fontSize: 16, lineHeight: 23, fontWeight: '600' }, heroPill: { alignSelf: 'flex-start', borderRadius: 99, paddingHorizontal: 10, paddingVertical: 6 }, statRow: { flexDirection: 'row', gap: 8 }, statCard: { flex: 1, borderWidth: 1, borderRadius: 18, justifyContent: 'center', gap: 1 }, statValue: { fontSize: 24, fontWeight: '900' }, statLabel: { fontSize: 13, lineHeight: 16 }, sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, settings: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, chipScroll: { marginHorizontal: -2 }, chips: { gap: 8, paddingHorizontal: 2, paddingVertical: 2 }, chip: { maxWidth: 230, minHeight: 44, justifyContent: 'center', borderWidth: 1, borderRadius: 14, paddingHorizontal: 12 }, listTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 2 }, listTitleText: { fontSize: 18, fontWeight: '900' }, filterEmpty: { borderRadius: 22, alignItems: 'center', gap: 8, padding: 28 }
});
