import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { Redirect, router } from 'expo-router';
import { AppButton, Eyebrow, Loadable, Screen, Title } from '@/src/components/ui';
import { AnimatedEntrance } from '@/src/components/motion';
import { getTheme } from '@/src/lib/tokens';
import { selectOffline, selectPendingCount, useAppStore } from '@/src/store/appStore';
import { useResponsiveLayout } from '@/src/hooks/useResponsiveLayout';

export default function SettingsScreen() {
  const session = useAppStore((state) => state.session); const offline = useAppStore(selectOffline); const pending = useAppStore(selectPendingCount); const setOffline = useAppStore((state) => state.setOffline); const sync = useAppStore((state) => state.syncPendingEdits); const signOut = useAppStore((state) => state.signOut); const [error, setError] = useState<Error | null>(null); const [working, setWorking] = useState(false); const t = getTheme(useColorScheme()); const layout = useResponsiveLayout();
  if (!session) return <Redirect href="/login" />;
  const syncNow = async () => { setWorking(true); setError(null); try { await sync(); } catch (cause) { setError(cause instanceof Error ? cause : new Error('Đồng bộ thất bại.')); } finally { setWorking(false); } };
  return <Screen padded={false}><Loadable loading={false} error={error} empty={false} retry={() => void syncNow()}><ScrollView contentContainerStyle={[styles.content, { paddingHorizontal: layout.horizontalPadding, paddingTop: layout.verticalPadding, gap: layout.compact ? 12 : 16 }]}><AnimatedEntrance><View style={[styles.profile, { padding: layout.compact ? 14 : 18, backgroundColor: t.accent, borderColor: t.accentStrong }]}><View style={[styles.avatar, { width: layout.compact ? 50 : 58, height: layout.compact ? 50 : 58, backgroundColor: t.primary }]}><Text style={{ fontSize: 24 }}>🌿</Text></View><View style={{ flex: 1, minWidth: 0 }}><Eyebrow>Tài khoản</Eyebrow><Title>Cài đặt</Title><Text numberOfLines={1} style={{ color: t.muted }}>{session}</Text></View></View></AnimatedEntrance><AnimatedEntrance delay={80}><Eyebrow>Đồng bộ dữ liệu</Eyebrow><View style={[styles.statusCard, { backgroundColor: t.surface, borderColor: t.border }]}><View style={[styles.statusIcon, { backgroundColor: offline ? t.warningSoft : t.primarySoft }]}><Text style={{ fontSize: 23 }}>{offline ? '☁️' : '✓'}</Text></View><View style={{ flex: 1, minWidth: 0 }}><Text style={{ color: t.text, fontWeight: '900' }}>{offline ? 'Đang ngoại tuyến' : 'Đang trực tuyến'}</Text><Text style={{ color: t.muted, marginTop: 3 }}>{pending ? `${pending} thay đổi đang chờ đồng bộ` : 'Dữ liệu đã được đồng bộ'}</Text></View></View><View style={styles.actions}><AppButton label={offline ? 'Bật lại kết nối' : 'Chuyển sang ngoại tuyến'} tone="secondary" onPress={() => setOffline(!offline)} /><AppButton label={working ? 'Đang đồng bộ...' : `Đồng bộ thay đổi${pending ? ` (${pending})` : ''}`} onPress={() => void syncNow()} disabled={working || offline || pending === 0} /></View></AnimatedEntrance><AnimatedEntrance delay={140}><Eyebrow>Tài khoản và ứng dụng</Eyebrow><View style={styles.actions}><AppButton label="Đăng xuất" tone="danger" onPress={() => void signOut()} /><AppButton label="← Quay lại khu vườn" tone="secondary" onPress={() => router.back()} /></View></AnimatedEntrance></ScrollView></Loadable></Screen>;
}

const styles = StyleSheet.create({ content: { paddingBottom: 32 }, profile: { borderWidth: 1, borderRadius: 24, flexDirection: 'row', alignItems: 'center', gap: 12 }, avatar: { borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, statusCard: { marginTop: 8, borderWidth: 1, borderRadius: 20, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 }, statusIcon: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, actions: { gap: 10 } });
